config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

product/urls.py
from django.urls import path
from django.views.generic import TemplateView

from product.views.product import CreateProductView, ProductsView, ProductsEditView
from product.views.variant import VariantView, VariantCreateView, VariantEditView

app_name = "product"

urlpatterns = [
    # Variants URLs
    path('variants/', VariantView.as_view(), name='variants'),
    path('variant/create', VariantCreateView.as_view(), name='create.variant'),
    path('variant/<int:id>/edit', VariantEditView.as_view(), name='update.variant'),

    # Products URLs
    path('create/', CreateProductView.as_view(), name='create.product'),
    path('list/', ProductsView.as_view(), name='list.product'),
    path('product/<int:id>/edit', ProductsEditView.as_view(), name='update.product'),

]

product/models.py
from django.db import models


# Create your models here.
class Variant(models.Model):
    title = models.CharField(max_length=40)
    description = models.TextField(null=True, blank=True)
    active = models.BooleanField(default=True)


class Product(models.Model):
    title = models.CharField(max_length=255)
    sku = models.SlugField(max_length=255)
    description = models.TextField()


class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.URLField()


class ProductVariant(models.Model):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class ProductVariantPrice(models.Model):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_one')
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_two')
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                              related_name='product_variant_three')
    price = models.FloatField()
    stock = models.FloatField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

product/forms.py
from django.forms import forms, ModelForm, CharField, TextInput, Textarea, BooleanField, CheckboxInput

from product.models import Variant


class VariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'})
        }

product/views/product.py
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView
from django.core.paginator import Paginator
from product.models import Variant, Product, ProductImage, ProductVariantPrice, ProductVariant
from django.db.models import Q


class BaseProductView(generic.View):
    model = Product
    template_name = 'products/list.html'


class CreateProductView(generic.TemplateView):
    template_name = 'products/create.html'

    def get_context_data(self, **kwargs):
        context = super(CreateProductView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True).values('id', 'title')
        context['product'] = True
        context['variants'] = list(variants.all())
        return context


# showing products and filter products
class ProductsView(generic.TemplateView):
    template_name = 'products/list.html'

    def get(self, request):
        # getting products data from ProductVariantPrice model
        products = ProductVariantPrice.objects.all()
        # getting variants
        variants = ProductVariant.objects.all()
        colors = []
        sizes = []
        styles = []
        for v in variants:
            if v.variant_id == 1:
                color = v.variant_title
                if color not in colors:
                    colors.append(color)
            if v.variant_id == 2:
                size = v.variant_title
                if size not in sizes:
                    sizes.append(size)
            if v.variant_id == 3:
                style = v.variant_title
                if style not in styles:
                    styles.append(style)
        print("variants: ", colors)
        # todo: pagination start
        paginator = Paginator(products, 10)
        page_number = request.GET.get("page", 1)
        page_obj = paginator.get_page(page_number)
        # todo: pagination end
        context = {
            # 'products': products,
            "page_obj": page_obj,
            "colors": colors,
            "sizes": sizes,
            "styles": styles,
        }
        return render(request, self.template_name, context=context)

    # post method for filtering
    def post(self, request):
        if request.method == "POST":
            # getting filter data
            name = request.POST.get('title')
            price_from = request.POST.get('price_from')
            price_to = request.POST.get('price_to')
            variant = request.POST.get('variant')
            product_ins = ProductVariantPrice.objects.all()
            # condition for not provided price
            if None or '' in [price_to, price_from, variant]:
                products = product_ins.filter(product__title__icontains=name)
                paginator = Paginator(products, 10)
                page_number = request.GET.get("page", 1)
                page_obj = paginator.get_page(page_number)
                print("filter by name: ", page_obj)
                context = {
                    'page_obj': page_obj
                }
                return render(request, 'products/filtered_products.html', context=context)
            else:
                products = product_ins.filter(
                    Q(product__title__icontains=name) | Q(price__gte=price_from) | Q(price__lte=price_to))

                paginator = Paginator(products, 10)
                page_number = request.GET.get("page", 1)
                page_obj = paginator.get_page(page_number)

                context = {
                    'page_obj': page_obj
                }
                return render(request, 'products/filtered_products.html', context=context)


# show single product and update product data
class ProductsEditView(generic.TemplateView):
    template_name = 'products/single_product.html'

    def get(self, request, id):
        # getting product data
        product = ProductVariantPrice.objects.get(id=id)
        context = {
            "product": product
        }
        return render(request, 'products/single_product.html', context=context)

    def post(self, request, id):
        # receiving input value for update product info
        title = request.POST.get("title")
        desc = request.POST.get("desc")
        sku = request.POST.get("sku")
        color = request.POST.get("color")
        size = request.POST.get("size")
        style = request.POST.get("style")

        # getting product instance
        product_ins = Product.objects.filter(id=id).first()
        # update product title, description, sku
        product_ins.title = title
        product_ins.description = desc
        product_ins.sku = sku
        product_ins.save()

        # getting variant instance and update product color
        variant_ins_color = ProductVariant.objects.filter(product_id=id, variant_id=1).first()
        variant_ins_color.variant_title = color
        variant_ins_color.save()

        # getting variant instance and update product size
        variant_ins_size = ProductVariant.objects.filter(product_id=id, variant_id=2).first()
        variant_ins_size.variant_title = size
        variant_ins_size.save()

        # getting variant instance and update product style
        variant_ins_style = ProductVariant.objects.filter(product_id=id, variant_id=3).first()
        variant_ins_style.variant_title = style
        variant_ins_style.save()

        return redirect('/product/list')

product/views/variant.py
from django.shortcuts import redirect
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView

from product.forms import VariantForm
from product.models import Variant


class BaseVariantView(generic.View):
    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'


class VariantView(BaseVariantView, ListView):
    template_name = 'variants/list.html'
    paginate_by = 10

    def get_queryset(self):
        filter_string = {}
        print(self.request.GET)
        for key in self.request.GET:
            if self.request.GET.get(key):
                filter_string[key] = self.request.GET.get(key)
        return Variant.objects.filter(**filter_string)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = True
        context['request'] = ''
        if self.request.GET:
            context['request'] = self.request.GET['title__icontains']
        return context


class VariantCreateView(BaseVariantView, CreateView):
    print("I am hitting")

    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'

    def form_valid(self, form):
        print("I am hitting")
        form.instance.user = self.request.user
        # super(BaseVariantView, self).form_valid(form)
        return super().form_valid(form)


class VariantEditView(BaseVariantView, UpdateView):
    pk_url_kwarg = 'id'

product/templates/variants/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Variant {% endblock %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Create Product Variant</h1>
        <a href="{% url 'product:variants' %}" class="float-right btn btn-primary">All Variant</a>
    </div>

    <div class="row justify-content-center">
        <form class="col-md-6" method="POST" novalidate>
            {% csrf_token %}
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form.title.label }}</label>
                        {{ form.title }}
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">{{ form.description.label }}</label>
                        {{ form.description }}
                    </div>
                    <div class="form-group form-check">
                        {{ form.active }}
                        <label class="form-check-label" for="active">{{ form.active.label }}</label>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

product/templates/variants/list.html
{% extends 'backend/base.html' %}

{% block title %} Create Variant {% endblock %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Product Variant</h1>
        <a href="{% url 'product:create.variant' %}" class="float-right btn btn-primary">+ New Variant</a>
    </div>

    <div class="card shadow mb-4">
        <form action="?" method="get" class="card-header py-3">
            <div class="form-row">
                <div class="col-md-3">
                    <input type="text" name="title__icontains" value="{{ request }}" placeholder="Search"
                           class="form-control">
                </div>
                <div class="col-md-1">
                    <button class="btn btn-primary">Search</button>
                </div>
            </div>
        </form>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Active</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for variant in variant_list %}
                        <tr>
                            <td>{{ variant.id }}</td>
                            <td>{{ variant.title }}</td>
                            <td>{{ variant.description }}</td>
                            <td>{{ variant.active }}</td>
                            <td>
                                <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                    <a href="{% url 'product:update.variant' variant.id %}"
                                       class="btn btn-primary">Edit</a>
                                    <button type="button" class="btn btn-danger">Delete</button>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer">
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="/product/variants/?browse={{ input }}&page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="/product/variants/?browse={{ input }}&page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock %}